name: CI

on:
  push:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Use latest Node.js
        uses: actions/setup-node@latest
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
